/**
 * Blog content loader.
 *
 * Reads blog posts from `apps/web/content/blog/*.html`. Each post is a
 * standalone HTML file with frontmatter (title, description, date,
 * author, categories).
 *
 * Posts are read at build time (or request time with `dynamic = "force-dynamic"`)
 * so new posts appear on the live site after a redeploy.
 *
 * The HTML is generated by HarborSEO (`scripts/harborseo.py`) and committed
 * to git, so the blog works offline and from the edge cache.
 */

import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const BLOG_DIR = path.join(process.cwd(), "content", "blog");

export type BlogPostMeta = {
  slug: string;
  title: string;
  description: string;
  publishedAt: string;
  updatedAt: string;
  author: string;
  categories: string[];
  wordCount?: number;
  coverImage?: string;
};

export type BlogPost = BlogPostMeta & {
  html: string;
  excerpt: string;
};

/** Strip HTML tags and trim to a one-paragraph excerpt (~200 chars). */
const makeExcerpt = (html: string, maxLen = 200): string => {
  const text = html
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&[a-z]+;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  if (text.length <= maxLen) return text;
  // Cut at the last word boundary within the limit
  const slice = text.slice(0, maxLen);
  const lastSpace = slice.lastIndexOf(" ");
  return `${slice.slice(0, lastSpace > 80 ? lastSpace : maxLen)}…`;
};

const parsePostFile = (filename: string): BlogPost | null => {
  const filePath = path.join(BLOG_DIR, filename);
  if (!filePath.endsWith(".html")) return null;

  const raw = fs.readFileSync(filePath, "utf8");
  const { data, content } = matter(raw);

  const slug = filename.replace(/\.html$/, "");
  const publishedAt = data.date
    ? new Date(data.date).toISOString()
    : new Date().toISOString();
  const updatedAt = data.updated
    ? new Date(data.updated).toISOString()
    : publishedAt;

  return {
    slug,
    title: data.title ?? slug,
    description: data.description ?? "",
    publishedAt,
    updatedAt,
    author: data.author ?? "Elixio Team",
    categories: Array.isArray(data.categories) ? data.categories : [],
    wordCount: data.wordCount,
    coverImage: data.coverImage,
    html: content,
    excerpt: data.description ?? makeExcerpt(content),
  };
};

const safeReadDir = (): string[] => {
  if (!fs.existsSync(BLOG_DIR)) return [];
  return fs.readdirSync(BLOG_DIR);
};

/** All blog posts, sorted newest first. */
export const getAllPosts = (): BlogPost[] => {
  const files = safeReadDir();
  return files
    .map((f) => parsePostFile(f))
    .filter((p): p is BlogPost => p !== null)
    .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
};

/** Single post by slug. */
export const getPostBySlug = (slug: string): BlogPost | null => {
  const filename = `${slug}.html`;
  if (!safeReadDir().includes(filename)) return null;
  return parsePostFile(filename);
};

/** All slugs — for generateStaticParams. */
export const getAllPostSlugs = (): string[] =>
  safeReadDir()
    .filter((f) => f.endsWith(".html"))
    .map((f) => f.replace(/\.html$/, ""));
};
